### PR TITLE
a few minor fixes

### PR DESCRIPTION
**Pull request by benediamond**
this PR would fix a few miscellaneous bugs, as well as apply `clang-format` to the whole project.

the diff is messy because of the code formatter, but the commit history below should spell things out pretty clearly. @mkoeppe let me know if you have any questions. thanks for your work.

### CODE REVIEW

**Comment by mkoeppe** [comment]
I don't think it's a good idea to apply a code formatter to a dead project.

**Comment by benediamond** [comment]
dead to whom 😃 I think this remains the best general-purpose elliptic curves + number theory library.

I can raise a new version without the code formatter, if you'd prefer.

P.S. Are you able to explain these CI build failures? [Possibly related](https://svn.boost.org/trac10/ticket/7270). Thanks.

**Comment by mkoeppe** [comment]
> I can raise a new version without the code formatter, if you'd prefer.

Yes please.

**Comment by benediamond** [comment]
@mkoeppe ok, this should do it. sorry for the force-pushes.

**Comment by benediamond** [comment]
I'll close this and re-raise with a clean version. Sorry & thanks.

**Pull request closed without merging**
